一、张量的数据类型

一般神经网络建模使用的都是torch.float32类型。


In [3]:
import numpy as np
import torch

# 自动推断数据类型

i, x, b = torch.tensor(1), torch.tensor(2.0), torch.tensor(True)
(i, i.dtype),  (x, x.dtype), (b, b.dtype)

((tensor(1), torch.int64),
 (tensor(2.), torch.float32),
 (tensor(True), torch.bool))

In [4]:
# 指定数据类型
i = torch.tensor(1.0).int()
i, i.dtype

(tensor(1, dtype=torch.int32), torch.int32)

二、 张量的维度
不同类型的数据可以用不同维度(dimension)的张量来表示。

标量为0维张量，向量为1维张量，矩阵为2维张量。

彩色图像有rgb三个通道，可以表示为3维张量。

视频还有时间维，可以表示为4维张量。

可以简单地总结为：有几层中括号，就是多少维的张量。

In [5]:
scalar = torch.tensor(True)
scalar, scalar.dim()

(tensor(True), 0)

In [9]:
vector = torch.tensor([1, 2, 3, 4]).float()
vector, vector.dim()

(tensor([1., 2., 3., 4.]), 1)

In [10]:
matrix = torch.tensor([[1,2,3], [4,5,6]])
matrix, matrix.dim()

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 2)

In [15]:
tensor3 = torch.tensor([[[1,2,3], [4,5,6]], [[7,8,9],[10,11, 12]]])
tensor3, tensor3.dim(), tensor3.size()

(tensor([[[ 1,  2,  3],
          [ 4,  5,  6]],
 
         [[ 7,  8,  9],
          [10, 11, 12]]]),
 3,
 torch.Size([2, 2, 3]))

三、 张量的尺寸
可以使用 shape属性或者 size()方法查看张量在每一维的长度.

可以使用view方法改变张量的尺寸。

如果view方法改变尺寸失败，可以使用reshape方法.

In [16]:
scalar, scalar.size(), scalar.shape

(tensor(True), torch.Size([]), torch.Size([]))

In [17]:
vector, vector.size(), vector.shape

(tensor([1., 2., 3., 4.]), torch.Size([4]), torch.Size([4]))

In [18]:
matrix, matrix.size(), matrix.shape

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 torch.Size([2, 3]),
 torch.Size([2, 3]))

In [22]:
# 使用view 可以改变张量尺寸
vector = torch.arange(12)
vector, vector.size(), vector.shape

(tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 torch.Size([12]),
 torch.Size([12]))

In [24]:
vector.view(4, -1), vector.shape

(tensor([[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]),
 torch.Size([12]))

In [28]:
matrix, matrix.is_contiguous()

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 True)

In [27]:
matrix62= matrix.t()
matrix62, matrix62.is_contiguous()

(tensor([[1, 4],
         [2, 5],
         [3, 6]]),
 False)

四、 张量和numpy 数组
可以用numpy方法从Tensor得到numpy数组，也可以用torch.from_numpy从numpy数组得到Tensor。

这两种方法关联的Tensor和numpy数组是共享数据内存的。

如果改变其中一个，另外一个的值也会发生改变。

如果有需要，可以用张量的clone方法拷贝张量，中断这种关联。

此外，还可以使用item方法从标量张量得到对应的Python数值。

使用tolist方法从张量得到对应的Python数值列表。

In [30]:
arr = np.zeros(3)
arr

array([0., 0., 0.])

In [31]:
tensor = torch.from_numpy(arr)
print('before add 1:', arr, tensor)

before add 1: [0. 0. 0.] tensor([0., 0., 0.], dtype=torch.float64)


In [32]:
print('after add 1:')
np.add(arr, 1, out=arr)
arr, tensor

after add 1:


(array([1., 1., 1.]), tensor([1., 1., 1.], dtype=torch.float64))

In [33]:
# .numpy() 方法可以从Tensor 得到numpy 数组
tensor = torch.zeros(3)
arr = tensor.numpy()
tensor, arr

(tensor([0., 0., 0.]), array([0., 0., 0.], dtype=float32))

In [34]:
#使用带下划线的方法表示计算结果会返回给调用 张量

tensor.add_(1)
tensor

tensor([1., 1., 1.])

In [35]:
# 可以用clone() 方法拷贝张量，中断这种关联

tensor = torch.zeros(3)

arr = tensor.clone().numpy()
print('befor add 1:')
tensor, arr

befor add 1:


(tensor([0., 0., 0.]), array([0., 0., 0.], dtype=float32))

In [36]:
print('after add 1')
tensor.add_(1)
tensor, arr

after add 1


(tensor([1., 1., 1.]), array([0., 0., 0.], dtype=float32))

In [37]:
# item方法和tolist方法可以将张量转换成Python数值和数值列表
scalar = torch.tensor(1)
s = scalar.item()

scalar, s

(tensor(1), 1)

In [38]:
tensor = torch.rand(2,2)
t = tensor.tolist()
t, type(t), tensor

([[0.969156801700592, 0.9278568625450134],
  [0.5598419904708862, 0.8579229116439819]],
 list,
 tensor([[0.9692, 0.9279],
         [0.5598, 0.8579]]))